# Generated by Django 4.1.7 on 2023-05-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdjangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmenu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
